#!/usr/bin/env python3
"""
Build a conservative Unity project source bundle for coding agents.

The bundle includes code, package manifests, project settings, and other small
text files that are useful to a coding agent. It excludes generated Unity
folders, local user settings, large files, binary assets, likely secrets, and
Unity editor-authored assets unless explicitly requested.

Expected repository layout:

    repo-root/
      Source/
        MyUnityProject/
          Assets/
          Packages/
          ProjectSettings/
      tools/
        build_unity_bundle.py
      docs/
        unity-bundle-tool.md

Example:

    python tools/build_unity_bundle.py MyUnityProject
    python tools/build_unity_bundle.py Source/MyUnityProject --dry-run
    python tools/build_unity_bundle.py MyUnityProject --include-editor-assets --max-file-mb 5
    python tools/build_unity_bundle.py MyUnityProject --scan-generated-dirs --full-json-manifest
    python tools/build_unity_bundle.py MyUnityProject --include-editor-assets --max-file-mb 2
    python tools/build_unity_bundle.py MyUnityProject --include-from ./unity-context.include --max-file-mb 13
"""

from __future__ import annotations

import argparse
import csv
import datetime as _dt
import fnmatch
import hashlib
import json
import os
import re
import sys
import zipfile
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Iterable, Optional

TOOL_VERSION = "0.3.1"

# Unity/editor-generated top-level directories. These are normally not useful for
# agent code review/editing and are expensive to share without Git LFS.
GENERATED_TOP_LEVEL_DIRS: dict[str, str] = {
    "Library": "Unity-generated asset import/cache data; regenerated by Unity from Assets, Packages, and ProjectSettings.",
    "Temp": "Unity temporary working files; regenerated as needed.",
    "Obj": "Generated build/intermediate output.",
    "Logs": "Editor/build logs; not source material.",
    "Build": "Build output; usually large and not hand-edited source.",
    "Builds": "Build output; usually large and not hand-edited source.",
    "MemoryCaptures": "Runtime/editor capture output; large diagnostic artifact.",
    "Recordings": "Capture/recording output; not source material for coding agents.",
    "UserSettings": "Unity user-local editor settings; regenerated per user and not needed for source-style sharing.",
    "AssetBundles": "Built asset bundle output; generated and often large.",
    "AddressableBuildData": "Generated Addressables build data; not source material.",
}

# Directories that are generally never source and can appear in many places.
ANYWHERE_GENERATED_DIRS = {
    ".git": "VCS metadata; never include in a source bundle.",
    ".hg": "VCS metadata; never include in a source bundle.",
    ".svn": "VCS metadata; never include in a source bundle.",
    ".vs": "IDE cache/workspace data; generated and user-local.",
    ".idea": "IDE workspace data; usually user-local.",
    "__pycache__": "Python bytecode cache; generated.",
    "node_modules": "Package-manager dependency cache/vendor tree; too large and reproducible from manifests.",
    ".pytest_cache": "Test cache; generated.",
    ".mypy_cache": "Type-checker cache; generated.",
    ".cache": "Tool cache; generated.",
}

# Unity/IDE generated files that should not be shared to coding agents.
GENERATED_FILE_PATTERNS = [
    "*.csproj",
    "*.sln",
    "*.suo",
    "*.user",
    "*.userprefs",
    "*.pidb",
    "*.booproj",
    "*.opendb",
    "*.VC.db",
    "*.pdb",
    "*.mdb",
    "*.tmp",
    "*.temp",
    "*.log",
    "*.bak",
    "*.swp",
    "*.orig",
    ".DS_Store",
    "Thumbs.db",
    "desktop.ini",
    "sysinfo.txt",
]

# Optional project-local pattern files. If present in a Unity project root,
# they are loaded automatically. This lets each project mark its own paid asset,
# vendor SDK, or custom source exceptions without editing this shared tool.
PROJECT_INCLUDE_PATTERN_FILENAMES = (
    ".unity-bundle-include",
    ".unity_bundle_include",
    "unity-bundle-include.txt",
)
PROJECT_EXCLUDE_PATTERN_FILENAMES = (
    ".unity-bundle-exclude",
    ".unity_bundle_exclude",
    "unity-bundle-exclude.txt",
)

# Path/name patterns that are likely secrets or machine-local credentials.
DEFAULT_SENSITIVE_PATTERNS = [
    ".env",
    ".env.*",
    "*.keystore",
    "*.jks",
    "*.p12",
    "*.pfx",
    "*.pem",
    "*.key",
    "*.mobileprovision",
    "*.provisionprofile",
    "*credential*",
    "*credentials*",
    "*secret*",
    "*secrets*",
    "*password*",
    "*privatekey*",
    "*private-key*",
    "local.properties",
    "google-services.json",
    "GoogleService-Info.plist",
    "ProjectSettings/UnityConnectSettings.asset",
    "ProjectSettings/ServicesCoreSettings.asset",
    "ProjectSettings/CloudProjectSettings.asset",
]

# Source-like and hand-editable files that coding agents can usually inspect or edit.
SOURCE_EXTENSIONS = {
    ".cs",
    ".asmdef",
    ".asmref",
    ".shader",
    ".compute",
    ".hlsl",
    ".cginc",
    ".glsl",
    ".glslinc",
    ".metal",
    ".uxml",
    ".uss",
    ".inputactions",
    ".rsp",
    ".java",
    ".kt",
    ".kts",
    ".c",
    ".cc",
    ".cpp",
    ".cxx",
    ".h",
    ".hpp",
    ".m",
    ".mm",
    ".swift",
    ".js",
    ".jslib",
    ".jsx",
    ".ts",
    ".tsx",
    ".py",
    ".lua",
    ".sh",
    ".bash",
    ".zsh",
    ".fish",
    ".bat",
    ".cmd",
    ".ps1",
    ".gradle",
}

TEXT_CONFIG_EXTENSIONS = {
    ".json",
    ".xml",
    ".yaml",
    ".yml",
    ".txt",
    ".md",
    ".markdown",
    ".csv",
    ".tsv",
    ".ini",
    ".cfg",
    ".conf",
    ".config",
    ".properties",
    ".props",
    ".targets",
    ".toml",
    ".ruleset",
}

# Unity serialized assets that are normally edited in the Unity Editor, not by hand.
# These can be included with --include-editor-assets if a coding agent needs scene/prefab context.
UNITY_EDITOR_AUTHORED_EXTENSIONS = {
    ".unity",
    ".prefab",
    ".asset",
    ".mat",
    ".anim",
    ".controller",
    ".overridecontroller",
    ".playable",
    ".mixer",
    ".physicmaterial",
    ".physicsmaterial2d",
    ".mask",
    ".spriteatlas",
    ".spriteatlasv2",
    ".terrainlayer",
    ".preset",
    ".guiskin",
    ".lighting",
    ".rendertexture",
    ".signal",
    ".tss",
    ".shadergraph",
    ".shadersubgraph",
    ".vfx",
    ".visualeffect",
}

# Known binary or asset-heavy file types. Most are source assets from an art/audio
# perspective, but not suitable for a compact code-agent bundle.
BINARY_OR_LARGE_ASSET_EXTENSIONS = {
    ".png",
    ".jpg",
    ".jpeg",
    ".gif",
    ".bmp",
    ".tga",
    ".tif",
    ".tiff",
    ".psd",
    ".psb",
    ".svg",
    ".svgz",
    ".ico",
    ".exr",
    ".hdr",
    ".fbx",
    ".blend",
    ".dae",
    ".3ds",
    ".max",
    ".ma",
    ".mb",
    ".obj",
    ".mtl",
    ".gltf",
    ".glb",
    ".abc",
    ".wav",
    ".mp3",
    ".ogg",
    ".aiff",
    ".aif",
    ".flac",
    ".m4a",
    ".mp4",
    ".mov",
    ".avi",
    ".webm",
    ".mkv",
    ".ttf",
    ".otf",
    ".woff",
    ".woff2",
    ".dll",
    ".so",
    ".dylib",
    ".a",
    ".lib",
    ".jar",
    ".aar",
    ".framework",
    ".bundle",
    ".exe",
    ".apk",
    ".aab",
    ".app",
    ".ipa",
    ".unitypackage",
    ".pdf",
    ".nupkg",
    ".tgz",
    ".zip",
    ".7z",
    ".rar",
    ".tar",
    ".gz",
    ".bz2",
    ".xz",
    ".bytes",
}

ROOT_TEXT_FILENAMES = {
    "README",
    "README.md",
    "README.markdown",
    "CHANGELOG",
    "CHANGELOG.md",
    "LICENSE",
    "LICENSE.md",
    "NOTICE",
    "NOTICE.md",
    ".gitignore",
    ".gitattributes",
    ".editorconfig",
    ".unity-bundle-include",
    ".unity_bundle_include",
    "unity-bundle-include.txt",
    ".unity-bundle-exclude",
    ".unity_bundle_exclude",
    "unity-bundle-exclude.txt",
}

DOC_ROOTS = {"docs", "Docs", "Documentation", "documentation"}

# Asset Store packages, SDK/vendor drops, and sample/example folders are often
# the biggest source of distracting noise in compact coding bundles. They are
# excluded by default, but explicit --include-pattern entries always override
# this list, and --include-vendor-assets disables it entirely.
DEFAULT_VENDOR_OR_SAMPLE_ASSET_PATTERNS = [
    # Generic vendor/import locations.
    "Assets/ThirdParty/",
    "Assets/Third Party/",
    "Assets/Vendor/",
    "Assets/Vendors/",
    "Assets/External/",
    "Assets/ExternalAssets/",
    "Assets/ImportedAssets/",
    "Assets/AssetStore/",
    "Assets/Asset Store/",
    "Assets/Plugins/NativeGallery/",
    # Common Unity/Asset Store package roots observed in real projects.
    "Assets/OpenCVForUnity/",
    "Assets/TextMesh Pro/",
    "Assets/TEXDraw/",
    "Assets/StandaloneFileBrowser/",
    "Assets/Black Whale Studio/",
    "Assets/DataDiagram/",
    "Assets/OBJImport/",
    "Assets/VSCode/",
    "Assets/Editor/Energise Software/",
    "Assets/Editor/Migration/",
    "Assets/TutorialInfo/",
    "Assets/NuGet/",
    "Assets/Packages/Newtonsoft.Json.*",
    "Assets/Packages/MathNet.Numerics.*",
    # Samples/examples/demos are useful in a full project but usually not in a
    # compact coding handoff unless the task is specifically about them.
    "Assets/**/Examples/**",
    "Assets/**/Example/**",
    "Assets/**/Samples/**",
    "Assets/**/Sample/**",
    "Assets/**/Demos/**",
    "Assets/**/Demo/**",
]

# Directory containers whose contents are usually native/binary plugin payloads,
# even when they contain source-looking files such as C/C++ headers or Info.plist.
# Explicit include patterns still override these exclusions.
BINARY_CONTAINER_DIR_SUFFIXES: dict[str, str] = {
    ".framework": "Apple framework bundle; native plugin/vendor SDK container, not hand-edited Unity project source.",
    ".xcframework": "Apple XCFramework bundle; native plugin/vendor SDK container, not hand-edited Unity project source.",
    ".bundle": "Native/plugin bundle directory; usually generated or vendor payload, not hand-edited Unity project source.",
    ".app": "Application bundle/build output; not source material.",
    ".appex": "Application extension bundle/build output; not source material.",
    ".dSYM": "Debug symbol bundle; generated diagnostic artifact.",
}

SECRET_CONTENT_PATTERNS = [
    re.compile(rb"-----BEGIN (?:RSA |DSA |EC |OPENSSH )?PRIVATE KEY-----"),
    re.compile(
        rb"(?i)\b(?:aws_secret_access_key|client_secret|refresh_token|private_key)\b\s*[:=]"
    ),
    re.compile(
        rb"(?i)\b(?:api[_-]?key|access[_-]?token|password)\b\s*[:=]\s*['\"]?[A-Za-z0-9_./+=:-]{16,}"
    ),
]


@dataclass
class Entry:
    path: Path
    rel_path: str
    entry_type: str
    size_bytes: Optional[int]
    mtime_utc: str
    is_symlink: bool = False


@dataclass
class Decision:
    rel_path: str
    entry_type: str
    status: str
    reason: str
    exclusion_reason: str
    file_kind: str
    size_bytes: Optional[int]
    mtime_utc: str
    sha256: str = ""
    zip_path: str = ""
    matched_rule: str = ""


@dataclass
class RuleContext:
    project_dir: Path
    output_zip: Path
    max_file_bytes: int
    include_editor_assets: bool
    include_unknown_text: bool
    include_all_meta: bool
    allow_binary: bool
    allow_sensitive: bool
    allow_potential_secrets: bool
    exclude_vendor_assets: bool
    hash_skipped: bool
    include_patterns: list[str]
    exclude_patterns: list[str]
    vendor_patterns: list[str]
    sensitive_patterns: list[str]


def utc_now_iso() -> str:
    return (
        _dt.datetime.now(_dt.timezone.utc)
        .replace(microsecond=0)
        .isoformat()
        .replace("+00:00", "Z")
    )


def mtime_to_iso(ts: float) -> str:
    return (
        _dt.datetime.fromtimestamp(ts, tz=_dt.timezone.utc)
        .replace(microsecond=0)
        .isoformat()
        .replace("+00:00", "Z")
    )


def rel_posix(path: Path, root: Path) -> str:
    return path.relative_to(root).as_posix()


def normalize_pattern(pattern: str) -> str:
    return pattern.strip().replace("\\", "/")


def read_patterns_file(path: Optional[Path], *, missing_ok: bool = False) -> list[str]:
    if not path:
        return []
    if not path.exists():
        if missing_ok:
            return []
        raise SystemExit(f"Pattern file does not exist: {path}")
    patterns: list[str] = []
    with path.open("r", encoding="utf-8") as f:
        for raw in f:
            line = raw.strip()
            if not line or line.startswith("#"):
                continue
            patterns.append(normalize_pattern(line))
    return patterns


def read_project_pattern_files(
    project_dir: Path, filenames: Iterable[str]
) -> tuple[list[str], list[str]]:
    patterns: list[str] = []
    sources: list[str] = []
    for filename in filenames:
        path = project_dir / filename
        if not path.is_file():
            continue
        loaded = read_patterns_file(path)
        if loaded:
            patterns.extend(loaded)
            sources.append(str(path))
    return patterns, sources


def globstar_zero_depth_variants(pattern: str) -> list[str]:
    """Return pattern variants where each /**/ may also match zero directories.

    Python's fnmatch treats * as matching slashes, but a pattern like
    Assets/Foo/**/*.asset still requires at least one slash between Foo and the
    filename. Unity bundle include files often use ** in the shell/globstar
    sense, where **/ means zero or more directories. These variants preserve the
    current fnmatch behavior while also handling the common zero-depth case.
    """
    variants = {pattern}
    changed = True
    while changed:
        changed = False
        for current in list(variants):
            start = 0
            while True:
                idx = current.find("/**/", start)
                if idx == -1:
                    break
                collapsed = current[:idx] + "/" + current[idx + len("/**/") :]
                if collapsed not in variants:
                    variants.add(collapsed)
                    changed = True
                start = idx + 1
    return sorted(variants)


def pattern_matches(pattern: str, rel_path: str) -> bool:
    pattern = normalize_pattern(pattern)
    rel_path = rel_path.replace("\\", "/")
    lower_pattern = pattern.lower()
    lower_rel = rel_path.lower()

    # Directory shorthand: "Assets/ThirdParty/" means the directory itself and
    # everything beneath it. Wildcards are supported too, e.g. "Assets/Foo*/".
    if lower_pattern.endswith("/"):
        for directory_pattern in globstar_zero_depth_variants(
            lower_pattern.rstrip("/")
        ):
            if lower_rel == directory_pattern or fnmatch.fnmatchcase(
                lower_rel, directory_pattern + "/*"
            ):
                return True

    # Exact path or fnmatch-style path. Treat /**/ as zero-or-more directories.
    for candidate_pattern in globstar_zero_depth_variants(lower_pattern):
        if fnmatch.fnmatchcase(lower_rel, candidate_pattern):
            return True

    # Filename-only shorthand, e.g. "*.keystore" or ".env".
    filename = lower_rel.rsplit("/", 1)[-1]
    if "/" not in lower_pattern and fnmatch.fnmatchcase(filename, lower_pattern):
        return True

    return False


def match_any(patterns: Iterable[str], rel_path: str) -> str:
    for pat in patterns:
        if pattern_matches(pat, rel_path):
            return pat
    return ""


def first_component(rel_path: str) -> str:
    return rel_path.split("/", 1)[0] if rel_path else ""


def components(rel_path: str) -> list[str]:
    return [p for p in rel_path.split("/") if p]


def suffix_lower(rel_path: str) -> str:
    return Path(rel_path).suffix.lower()


def summary_root_key(rel_path: str) -> str:
    parts = rel_path.split("/")
    if not parts:
        return ""
    if parts[0] == "Assets" and len(parts) > 1:
        return f"Assets/{parts[1]}"
    if parts[0] == "Packages" and len(parts) > 1:
        return f"Packages/{parts[1]}"
    if parts[0] == "ProjectSettings":
        return "ProjectSettings"
    return parts[0]


def format_bytes(num_bytes: Optional[int]) -> str:
    if num_bytes is None:
        return "unknown"
    value = float(num_bytes)
    for unit in ("B", "KiB", "MiB", "GiB"):
        if value < 1024 or unit == "GiB":
            if unit == "B":
                return f"{int(value)} {unit}"
            return f"{value:.2f} {unit}"
        value /= 1024
    return f"{value:.2f} GiB"


def is_under_root(rel_path: str, root: str) -> bool:
    return rel_path == root or rel_path.startswith(root + "/")


def binary_container_directory_reason(rel_path: str) -> tuple[str, str]:
    for comp in components(rel_path):
        lower_comp = comp.lower()
        for suffix, reason in BINARY_CONTAINER_DIR_SUFFIXES.items():
            if lower_comp.endswith(suffix.lower()):
                return comp, reason
    return "", ""


def generated_directory_reason(rel_path: str) -> tuple[str, str]:
    comp = first_component(rel_path)
    if comp in GENERATED_TOP_LEVEL_DIRS:
        return comp, GENERATED_TOP_LEVEL_DIRS[comp]
    for comp in components(rel_path):
        if comp in ANYWHERE_GENERATED_DIRS:
            return comp, ANYWHERE_GENERATED_DIRS[comp]
    comp, reason = binary_container_directory_reason(rel_path)
    if comp:
        return comp, reason
    return "", ""


def vendor_or_sample_pattern(rel_path: str, ctx: RuleContext) -> str:
    if not ctx.exclude_vendor_assets:
        return ""
    return match_any(ctx.vendor_patterns, rel_path)


def generated_file_pattern(rel_path: str) -> str:
    return match_any(GENERATED_FILE_PATTERNS, rel_path)


def read_sample(path: Path, limit: int = 8192) -> bytes:
    with path.open("rb") as f:
        return f.read(limit)


def is_probably_text_file(path: Path, sample_limit: int = 8192) -> bool:
    try:
        sample = read_sample(path, sample_limit)
    except OSError:
        return False
    if not sample:
        return True
    if b"\x00" in sample:
        return False
    if sample.startswith((b"\xef\xbb\xbf", b"\xff\xfe", b"\xfe\xff")):
        return True
    try:
        sample.decode("utf-8")
        return True
    except UnicodeDecodeError:
        pass

    # Conservative fallback for single-byte text encodings.
    printable = bytes(range(32, 127)) + b"\n\r\t\b\f"
    nontext = sample.translate(None, printable)
    return (len(nontext) / max(len(sample), 1)) < 0.05


def has_potential_secret_content(path: Path, scan_limit: int = 262_144) -> bool:
    try:
        sample = read_sample(path, scan_limit)
    except OSError:
        return False
    return any(pattern.search(sample) for pattern in SECRET_CONTENT_PATTERNS)


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def file_too_large(entry: Entry, ctx: RuleContext) -> bool:
    return entry.size_bytes is not None and entry.size_bytes > ctx.max_file_bytes


def skip_decision(
    entry: Entry, reason: str, file_kind: str, matched_rule: str = ""
) -> Decision:
    return Decision(
        rel_path=entry.rel_path,
        entry_type=entry.entry_type,
        status="skipped",
        reason=reason,
        exclusion_reason=reason,
        file_kind=file_kind,
        size_bytes=entry.size_bytes,
        mtime_utc=entry.mtime_utc,
        matched_rule=matched_rule,
    )


def include_decision(
    entry: Entry, reason: str, file_kind: str, zip_root: str, matched_rule: str = ""
) -> Decision:
    zip_path = f"{zip_root}/{entry.rel_path}" if zip_root else entry.rel_path
    return Decision(
        rel_path=entry.rel_path,
        entry_type=entry.entry_type,
        status="included",
        reason=reason,
        exclusion_reason="",
        file_kind=file_kind,
        size_bytes=entry.size_bytes,
        mtime_utc=entry.mtime_utc,
        zip_path=zip_path,
        matched_rule=matched_rule,
    )


def error_decision(entry: Entry, reason: str) -> Decision:
    return Decision(
        rel_path=entry.rel_path,
        entry_type=entry.entry_type,
        status="error",
        reason=reason,
        exclusion_reason=reason,
        file_kind="error",
        size_bytes=entry.size_bytes,
        mtime_utc=entry.mtime_utc,
    )


def safe_text_include(
    entry: Entry,
    ctx: RuleContext,
    zip_root: str,
    reason: str,
    file_kind: str,
    matched_rule: str = "",
    allow_binary_for_explicit_include: bool = False,
) -> Decision:
    if file_too_large(entry, ctx):
        mb = (entry.size_bytes or 0) / (1024 * 1024)
        return skip_decision(
            entry,
            f"Excluded: file is {mb:.2f} MiB, above --max-file-mb ({ctx.max_file_bytes / (1024 * 1024):.2f} MiB).",
            "large_file",
            matched_rule,
        )

    is_text = is_probably_text_file(entry.path)
    if not is_text and not (allow_binary_for_explicit_include and ctx.allow_binary):
        return skip_decision(
            entry,
            "Excluded: file appears to be binary or non-text.",
            "binary_or_non_text",
            matched_rule,
        )

    if (
        is_text
        and not ctx.allow_potential_secrets
        and has_potential_secret_content(entry.path)
    ):
        return skip_decision(
            entry,
            "Excluded: text content matched a high-confidence potential-secret pattern. Use --allow-potential-secrets only after reviewing.",
            "potential_secret_content",
            matched_rule,
        )

    return include_decision(entry, reason, file_kind, zip_root, matched_rule)


def hard_safety_exclusion(entry: Entry, ctx: RuleContext) -> Optional[Decision]:
    rel = entry.rel_path

    if entry.is_symlink:
        return skip_decision(
            entry,
            "Excluded: symlink not followed or included, to avoid bundling files outside the Unity project.",
            "symlink",
        )

    # Avoid including the bundle itself if the caller writes it inside the project.
    try:
        if ctx.output_zip.resolve() == entry.path.resolve():
            return skip_decision(
                entry, "Excluded: output zip file itself.", "output_artifact"
            )
    except OSError:
        pass

    explicit_exclude = match_any(ctx.exclude_patterns, rel)
    if explicit_exclude:
        return skip_decision(
            entry,
            f"Excluded: matched --exclude-pattern / exclude file pattern '{explicit_exclude}'.",
            "explicit_exclude",
            explicit_exclude,
        )

    if not ctx.allow_sensitive:
        sensitive_match = match_any(ctx.sensitive_patterns, rel)
        if sensitive_match:
            return skip_decision(
                entry,
                f"Excluded: path/name matched sensitive-file pattern '{sensitive_match}'. Use --allow-sensitive only after reviewing.",
                "sensitive_path",
                sensitive_match,
            )

    return None


def classify_non_meta(entry: Entry, ctx: RuleContext, zip_root: str) -> Decision:
    rel = entry.rel_path
    ext = suffix_lower(rel)
    filename = Path(rel).name

    hard = hard_safety_exclusion(entry, ctx)
    if hard:
        return hard

    explicit_include = match_any(ctx.include_patterns, rel)

    gen_dir, gen_reason = generated_directory_reason(rel)
    if gen_dir and not explicit_include:
        return skip_decision(
            entry,
            f"Excluded: {gen_reason}",
            "generated_or_user_local_directory",
            gen_dir,
        )

    gen_file = generated_file_pattern(rel)
    if gen_file and not explicit_include:
        return skip_decision(
            entry,
            f"Excluded: generated/tool artifact matching '{gen_file}'.",
            "generated_file",
            gen_file,
        )

    if explicit_include:
        return safe_text_include(
            entry,
            ctx,
            zip_root,
            f"Included: matched explicit include pattern '{explicit_include}'.",
            "explicit_include",
            explicit_include,
            allow_binary_for_explicit_include=True,
        )

    vendor_match = vendor_or_sample_pattern(rel, ctx)
    if vendor_match:
        return skip_decision(
            entry,
            f"Excluded: matched likely third-party/vendor/sample asset pattern '{vendor_match}'. Use --include-vendor-assets or a targeted --include-pattern if the agent needs it.",
            "vendor_or_sample_asset",
            vendor_match,
        )

    if ext in BINARY_OR_LARGE_ASSET_EXTENSIONS:
        return skip_decision(
            entry,
            f"Excluded: '{ext}' is treated as a binary/large asset type, not coding-agent source.",
            "binary_or_large_asset",
        )

    # Root-level documentation/config worth showing to the agent.
    if "/" not in rel and filename in ROOT_TEXT_FILENAMES:
        return safe_text_include(
            entry,
            ctx,
            zip_root,
            "Included: root documentation or repository config.",
            "root_text_file",
        )

    # Project-local docs.
    if first_component(rel) in DOC_ROOTS and ext in (
        SOURCE_EXTENSIONS | TEXT_CONFIG_EXTENSIONS
    ):
        return safe_text_include(
            entry,
            ctx,
            zip_root,
            "Included: project documentation/source-like text under docs.",
            "documentation",
        )

    # Unity ProjectSettings are text in most modern Unity projects and useful for agent context.
    if is_under_root(rel, "ProjectSettings"):
        if ext in BINARY_OR_LARGE_ASSET_EXTENSIONS:
            return skip_decision(
                entry,
                f"Excluded: ProjectSettings file uses binary/large extension '{ext}'.",
                "binary_project_setting",
            )
        return safe_text_include(
            entry,
            ctx,
            zip_root,
            "Included: Unity ProjectSettings text/configuration file.",
            "project_settings",
        )

    # UPM package manifests and embedded package source/config.
    if is_under_root(rel, "Packages"):
        if filename in {"manifest.json", "packages-lock.json", "package.json"}:
            return safe_text_include(
                entry,
                ctx,
                zip_root,
                "Included: Unity Package Manager/package manifest.",
                "package_manifest",
            )
        if ext in SOURCE_EXTENSIONS:
            return safe_text_include(
                entry,
                ctx,
                zip_root,
                "Included: source-like file inside Packages.",
                "package_source",
            )
        if ext in TEXT_CONFIG_EXTENSIONS:
            return safe_text_include(
                entry,
                ctx,
                zip_root,
                "Included: text config/docs inside Packages.",
                "package_text_config",
            )
        if ext in UNITY_EDITOR_AUTHORED_EXTENSIONS:
            if ctx.include_editor_assets:
                return safe_text_include(
                    entry,
                    ctx,
                    zip_root,
                    "Included: Unity editor-authored package asset because --include-editor-assets was used.",
                    "unity_editor_authored_asset",
                )
            return skip_decision(
                entry,
                "Excluded: Unity editor-authored package asset; use --include-editor-assets if the agent needs this context.",
                "unity_editor_authored_asset",
            )
        return skip_decision(
            entry,
            "Excluded: Packages file type is not recognized as small source/config text.",
            "unrecognized_package_file",
        )

    # The main Assets tree: include hand-editable code/text, skip Unity editor-authored assets unless requested.
    if is_under_root(rel, "Assets"):
        if ext in SOURCE_EXTENSIONS:
            return safe_text_include(
                entry,
                ctx,
                zip_root,
                "Included: source-like file under Assets.",
                "asset_source",
            )
        if ext in TEXT_CONFIG_EXTENSIONS:
            return safe_text_include(
                entry,
                ctx,
                zip_root,
                "Included: text config/docs/data under Assets.",
                "asset_text_config",
            )
        if ext in UNITY_EDITOR_AUTHORED_EXTENSIONS:
            if ctx.include_editor_assets:
                return safe_text_include(
                    entry,
                    ctx,
                    zip_root,
                    "Included: Unity editor-authored asset because --include-editor-assets was used.",
                    "unity_editor_authored_asset",
                )
            return skip_decision(
                entry,
                "Excluded: Unity editor-authored asset normally edited in the Unity Editor; use --include-editor-assets for scene/prefab/material context.",
                "unity_editor_authored_asset",
            )
        if ctx.include_unknown_text:
            return safe_text_include(
                entry,
                ctx,
                zip_root,
                "Included: unknown small text file because --include-unknown-text was used.",
                "unknown_text",
            )
        return skip_decision(
            entry,
            "Excluded: Assets file type is not recognized as hand-editable code/config and is not included by default.",
            "unrecognized_asset_file",
        )

    # Some projects keep standalone package.json or tool config at the project root.
    if "/" not in rel and ext in TEXT_CONFIG_EXTENSIONS:
        return safe_text_include(
            entry,
            ctx,
            zip_root,
            "Included: root-level text configuration/documentation file.",
            "root_text_config",
        )

    return skip_decision(
        entry,
        "Excluded: outside default Unity source roots (Assets, Packages, ProjectSettings, project docs/root configs).",
        "outside_default_roots",
    )


def classify_meta(
    entry: Entry,
    ctx: RuleContext,
    zip_root: str,
    included_files: set[str],
    included_dirs: set[str],
) -> Decision:
    rel = entry.rel_path

    hard = hard_safety_exclusion(entry, ctx)
    if hard:
        return hard

    explicit_include = match_any(ctx.include_patterns, rel)
    gen_dir, gen_reason = generated_directory_reason(rel)
    if gen_dir and not explicit_include:
        return skip_decision(
            entry,
            f"Excluded: {gen_reason}",
            "generated_or_user_local_directory",
            gen_dir,
        )

    if explicit_include:
        return safe_text_include(
            entry,
            ctx,
            zip_root,
            f"Included: .meta matched explicit include pattern '{explicit_include}'.",
            "meta",
            explicit_include,
        )

    paired_rel = rel[:-5]  # strip trailing .meta
    paired_is_included_file = paired_rel in included_files
    paired_is_included_dir = paired_rel in included_dirs

    if paired_is_included_file:
        return safe_text_include(
            entry,
            ctx,
            zip_root,
            "Included: Unity .meta companion for an included asset, preserving GUID/import settings.",
            "meta",
        )
    if paired_is_included_dir:
        return safe_text_include(
            entry,
            ctx,
            zip_root,
            "Included: Unity .meta companion for a folder containing included assets.",
            "folder_meta",
        )

    vendor_match = vendor_or_sample_pattern(rel, ctx) or vendor_or_sample_pattern(
        paired_rel, ctx
    )
    if vendor_match:
        return skip_decision(
            entry,
            f"Excluded: .meta belongs to a likely third-party/vendor/sample asset pattern '{vendor_match}'. Use --include-vendor-assets or a targeted --include-pattern if needed.",
            "vendor_or_sample_meta",
            vendor_match,
        )

    if ctx.include_all_meta and (
        is_under_root(rel, "Assets")
        or is_under_root(rel, "Packages")
        or rel in {"Assets.meta", "Packages.meta"}
    ):
        return safe_text_include(
            entry,
            ctx,
            zip_root,
            "Included: --include-all-meta requested all safe Unity .meta files.",
            "meta",
        )

    return skip_decision(
        entry,
        "Excluded: Unity .meta file whose paired asset/folder is not included in this source bundle.",
        "unpaired_or_excluded_meta",
    )


def iter_project_entries(
    project_dir: Path, prune_generated_dirs: bool
) -> Iterable[Entry]:
    """Yield file entries. When prune_generated_dirs is true, emitted directory
    marker rows document the pruning, but files inside those dirs are not listed.
    """
    project_dir = project_dir.resolve()
    for root, dirs, files in os.walk(project_dir, topdown=True, followlinks=False):
        root_path = Path(root)

        if prune_generated_dirs:
            keep_dirs: list[str] = []
            for d in dirs:
                dir_path = root_path / d
                rel = rel_posix(dir_path, project_dir)
                gen_dir, gen_reason = generated_directory_reason(rel)
                try:
                    st = dir_path.lstat()
                    mtime = mtime_to_iso(st.st_mtime)
                except OSError:
                    st = None
                    mtime = ""
                if gen_dir:
                    yield Entry(
                        path=dir_path,
                        rel_path=rel + "/",
                        entry_type="directory",
                        size_bytes=None,
                        mtime_utc=mtime,
                        is_symlink=dir_path.is_symlink(),
                    )
                    continue
                keep_dirs.append(d)
            dirs[:] = keep_dirs

        for name in files:
            path = root_path / name
            try:
                st = path.lstat()
                size = st.st_size
                mtime = mtime_to_iso(st.st_mtime)
                is_link = path.is_symlink()
            except OSError:
                size = None
                mtime = ""
                is_link = False
            yield Entry(
                path=path,
                rel_path=rel_posix(path, project_dir),
                entry_type="file",
                size_bytes=size,
                mtime_utc=mtime,
                is_symlink=is_link,
            )


def resolve_repo_root(script_path: Path, explicit_repo_root: Optional[Path]) -> Path:
    if explicit_repo_root:
        return explicit_repo_root.resolve()
    # Expected location: repo-root/tools/build_unity_bundle.py
    if script_path.parent.name == "tools":
        return script_path.parent.parent.resolve()
    return Path.cwd().resolve()


def resolve_project_dir(repo_root: Path, project_arg: str) -> Path:
    project_path = Path(project_arg)
    candidates: list[Path] = []

    if project_path.is_absolute():
        candidates.append(project_path)
    else:
        candidates.append(repo_root.parent / project_path)
        candidates.append(repo_root / project_path)
        candidates.append(Path.cwd() / project_path)

    for candidate in candidates:
        if candidate.exists() and candidate.is_dir():
            return candidate.resolve()

    tried = "\n  ".join(str(c) for c in candidates)
    raise SystemExit(
        f"Could not find project directory for '{project_arg}'. Tried:\n  {tried}"
    )


def validate_unity_project(project_dir: Path, allow_non_unity: bool) -> None:
    assets = project_dir / "Assets"
    project_settings = project_dir / "ProjectSettings"
    packages = project_dir / "Packages"
    if assets.is_dir() and project_settings.is_dir():
        return
    if allow_non_unity:
        return
    raise SystemExit(
        f"'{project_dir}' does not look like a Unity project: expected at least Assets/ and ProjectSettings/. "
        "Use --allow-non-unity only if this is intentional."
    )


def build_included_dir_set(included_files: set[str]) -> set[str]:
    dirs: set[str] = set()
    for rel in included_files:
        parts = rel.split("/")[:-1]
        acc: list[str] = []
        for part in parts:
            acc.append(part)
            dirs.add("/".join(acc))
    return dirs


def write_manifest_csv(path: Path, decisions: list[Decision]) -> None:
    fieldnames = [
        "rel_path",
        "entry_type",
        "status",
        "file_kind",
        "size_bytes",
        "mtime_utc",
        "sha256",
        "zip_path",
        "matched_rule",
        "reason",
        "exclusion_reason",
    ]
    with path.open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        for d in decisions:
            writer.writerow({k: getattr(d, k) for k in fieldnames})


def write_manifest_json(path: Path, decisions: list[Decision], summary: dict) -> None:
    payload = {
        "summary": summary,
        "files": [asdict(d) for d in decisions],
    }
    with path.open("w", encoding="utf-8") as f:
        json.dump(payload, f, indent=2, ensure_ascii=False)
        f.write("\n")


def write_summary_json(path: Path, summary: dict) -> None:
    with path.open("w", encoding="utf-8") as f:
        json.dump(summary, f, indent=2, ensure_ascii=False)
        f.write("\n")


def make_agent_readme(project_name: str, summary: dict) -> str:
    roots = summary.get("included_top_roots_by_bytes", [])[:10]
    if roots:
        roots_md = "\n".join(
            f"- `{item['path']}`: {item['files']} files, {format_bytes(item['bytes'])}"
            for item in roots
        )
    else:
        roots_md = "- None"

    json_note = ""
    if not summary.get("full_json_manifest"):
        json_note = (
            "\nA compact `BUNDLE_SUMMARY.json` is included. A full row-by-row "
            "`BUNDLE_MANIFEST.json` is only included when `--full-json-manifest` is used."
        )

    if summary.get("prune_generated_dirs"):
        generated_note = (
            "Known generated/cache/native-container directories were pruned. The CSV manifest records "
            "directory markers for those folders instead of enumerating every generated file. Re-run with "
            "`--scan-generated-dirs` when an exhaustive generated-file listing is needed."
        )
    else:
        generated_note = (
            "Known generated/cache/native-container directories were scanned file-by-file. This gives a fuller "
            "inventory but can make manifests very large."
        )

    vendor_note = (
        "Likely third-party/vendor/sample asset trees were excluded by default. Re-run with "
        "`--include-vendor-assets` or use a targeted `--include-pattern` if a task needs dependency source."
        if summary.get("exclude_vendor_assets")
        else "Likely third-party/vendor/sample asset tree exclusions were disabled for this bundle."
    )

    return f"""# Coding Bundle: {project_name}

This zip is a **curated Unity source bundle**, not a complete Unity project backup.
It intentionally omits generated folders, large/binary assets, user-local files,
likely secrets, native/plugin SDK containers, likely vendor/sample assets, and
Unity editor-authored assets that are normally not edited by hand.

## What is inside

- Code and source-like text files selected by `tools/build_unity_bundle.py`.
- Unity `Packages/` manifests and safe embedded package source/config.
- Small text files under `ProjectSettings/` for project context.
- `.meta` files when their paired asset or containing folder is included.
- `BUNDLE_MANIFEST.csv`, listing scanned original entries and the include/exclude reason for each.
- `BUNDLE_SUMMARY.json`, with counts and the largest included roots.{json_note}
- `BUNDLE_REVIEW_FLAGS.md`, highlighting omitted build scenes, skipped source-like files, and other context that may matter for a coding task.

## Generated-folder scan note

{generated_note}

## Vendor/sample asset note

{vendor_note}

## Summary

- Generated at: {summary.get('generated_at_utc')}
- Tool version: {summary.get('tool_version')}
- Project: {summary.get('project_name')}
- Scanned file entries: {summary.get('scanned_file_entries')}
- Included files: {summary.get('included_files')}
- Skipped files: {summary.get('skipped_files')}
- Error entries: {summary.get('error_entries')}
- Included bytes: {format_bytes(summary.get('included_bytes'))}

## Largest included roots by raw size

{roots_md}

Review `BUNDLE_REVIEW_FLAGS.md` and the manifest before using or sharing this bundle. If a task needs scene,
prefab, material, input-binding, or other Unity Editor context, re-run with
`--include-editor-assets` and an appropriate `--max-file-mb` value, or add a targeted `--include-pattern`.
"""


def extract_editor_build_scenes(project_dir: Path) -> list[dict[str, object]]:
    """Extract scene paths from ProjectSettings/EditorBuildSettings.asset.

    This is intentionally a light-weight parser for UnityYAML. It avoids a YAML
    dependency and only looks for the m_Scenes entries that Unity writes as
    enabled/path/guid records.
    """
    path = project_dir / "ProjectSettings" / "EditorBuildSettings.asset"
    if not path.is_file():
        return []

    scenes: list[dict[str, object]] = []
    current: Optional[dict[str, object]] = None
    try:
        lines = path.read_text(encoding="utf-8", errors="replace").splitlines()
    except OSError:
        return []

    for raw in lines:
        line = raw.strip()
        if line.startswith("- enabled:"):
            if current and current.get("path"):
                scenes.append(current)
            enabled_value = line.split(":", 1)[1].strip()
            current = {
                "enabled": enabled_value in {"1", "true", "True"},
                "path": "",
                "guid": "",
            }
            continue
        if current is None:
            continue
        if line.startswith("path:"):
            current["path"] = line.split(":", 1)[1].strip()
        elif line.startswith("guid:"):
            current["guid"] = line.split(":", 1)[1].strip()

    if current and current.get("path"):
        scenes.append(current)
    return scenes


def decision_ref(decision: Optional[Decision]) -> dict[str, object]:
    if decision is None:
        return {
            "status": "missing_from_scan",
            "file_kind": "missing_from_scan",
            "size_bytes": None,
            "reason": "Path was referenced by project settings but was not encountered during the scan.",
            "matched_rule": "",
        }
    return {
        "status": decision.status,
        "file_kind": decision.file_kind,
        "size_bytes": decision.size_bytes,
        "reason": decision.reason,
        "matched_rule": decision.matched_rule,
    }


def build_review_flags(
    decisions: list[Decision], project_dir: Path, args: argparse.Namespace
) -> dict[str, object]:
    """Build a compact, human-readable risk report from the classification decisions.

    The report is not meant to be exhaustive. It surfaces places where a coding
    agent may miss important context despite the bundle being intentionally safe
    and compact.
    """
    by_rel = {d.rel_path: d for d in decisions}

    editor_build_scenes: list[dict[str, object]] = []
    for scene in extract_editor_build_scenes(project_dir):
        rel = str(scene.get("path") or "").replace("\\", "/")
        decision = by_rel.get(rel)
        ref = decision_ref(decision)
        editor_build_scenes.append(
            {
                "path": rel,
                "enabled": bool(scene.get("enabled")),
                "guid": str(scene.get("guid") or ""),
                **ref,
            }
        )

    omitted_build_scenes = [
        s for s in editor_build_scenes if s.get("status") != "included"
    ]

    source_exts = SOURCE_EXTENSIONS
    skipped_source_like = [
        d
        for d in decisions
        if d.status == "skipped"
        and d.entry_type == "file"
        and suffix_lower(d.rel_path) in source_exts
    ]
    skipped_nonvendor_source_like = [
        d
        for d in skipped_source_like
        if d.file_kind not in {"vendor_or_sample_asset", "vendor_or_sample_meta"}
    ]

    skipped_editor_assets = [
        d
        for d in decisions
        if d.status == "skipped"
        and d.entry_type == "file"
        and d.file_kind == "unity_editor_authored_asset"
    ]
    skipped_editor_assets_sorted = sorted(
        skipped_editor_assets, key=lambda d: d.size_bytes or 0, reverse=True
    )

    included_large_text = sorted(
        [
            d
            for d in decisions
            if d.status == "included"
            and d.entry_type == "file"
            and (d.size_bytes or 0) >= int(args.review_large_included_kb * 1024)
        ],
        key=lambda d: d.size_bytes or 0,
        reverse=True,
    )

    def compact_decisions(items: list[Decision], limit: int) -> list[dict[str, object]]:
        return [
            {
                "path": d.rel_path,
                "size_bytes": d.size_bytes,
                "file_kind": d.file_kind,
                "reason": d.reason,
                "matched_rule": d.matched_rule,
            }
            for d in items[:limit]
        ]

    include_pattern_checks: list[dict[str, object]] = []
    include_pattern_problems: list[dict[str, object]] = []
    for pattern in getattr(args, "_effective_include_patterns", []):
        matched = [
            d
            for d in decisions
            if d.entry_type == "file" and pattern_matches(pattern, d.rel_path)
        ]
        included_matches = [d for d in matched if d.status == "included"]
        skipped_matches = [d for d in matched if d.status == "skipped"]
        check = {
            "pattern": pattern,
            "matched_files": len(matched),
            "included_files": len(included_matches),
            "skipped_files": len(skipped_matches),
            "skipped_top": compact_decisions(
                sorted(skipped_matches, key=lambda d: d.size_bytes or 0, reverse=True),
                min(args.review_list_limit, 5),
            ),
        }
        include_pattern_checks.append(check)
        if not matched or not included_matches or skipped_matches:
            include_pattern_problems.append(check)

    return {
        "editor_build_scenes": editor_build_scenes,
        "omitted_build_scenes_count": len(omitted_build_scenes),
        "omitted_build_scenes": omitted_build_scenes,
        "skipped_source_like_files_count": len(skipped_source_like),
        "skipped_vendor_source_like_files_count": len(skipped_source_like)
        - len(skipped_nonvendor_source_like),
        "skipped_nonvendor_source_like_files_count": len(skipped_nonvendor_source_like),
        "skipped_nonvendor_source_like_files_top": compact_decisions(
            sorted(
                skipped_nonvendor_source_like,
                key=lambda d: d.size_bytes or 0,
                reverse=True,
            ),
            args.review_list_limit,
        ),
        "skipped_editor_authored_context_count": len(skipped_editor_assets),
        "skipped_editor_authored_context_bytes": sum(
            d.size_bytes or 0 for d in skipped_editor_assets
        ),
        "skipped_editor_authored_context_top": compact_decisions(
            skipped_editor_assets_sorted, args.review_list_limit
        ),
        "large_included_files_count": len(included_large_text),
        "large_included_files_top": compact_decisions(
            included_large_text, args.review_list_limit
        ),
        "explicit_include_patterns_count": len(include_pattern_checks),
        "explicit_include_pattern_problems_count": len(include_pattern_problems),
        "explicit_include_pattern_problems": include_pattern_problems[
            : args.review_list_limit
        ],
    }


def make_review_report(
    project_name: str, summary: dict, review_flags: dict[str, object]
) -> str:
    def fmt_size(value: object) -> str:
        return format_bytes(value if isinstance(value, int) else None)

    omitted_scenes = review_flags.get("omitted_build_scenes", []) or []
    editor_context_top = (
        review_flags.get("skipped_editor_authored_context_top", []) or []
    )
    skipped_source_top = (
        review_flags.get("skipped_nonvendor_source_like_files_top", []) or []
    )
    large_included_top = review_flags.get("large_included_files_top", []) or []

    lines: list[str] = []
    lines.append(f"# Bundle Review Flags: {project_name}")
    lines.append("")
    lines.append(
        "This file highlights review items that may matter to a coding agent. These are not necessarily mistakes; the bundle is intentionally conservative."
    )
    lines.append("")

    lines.append("## Build scenes")
    if omitted_scenes:
        lines.append(
            f"{len(omitted_scenes)} scene(s) referenced by `ProjectSettings/EditorBuildSettings.asset` were not included in the bundle:"  # type: ignore
        )
        lines.append("")
        for item in omitted_scenes:  # type: ignore
            enabled = "enabled" if item.get("enabled") else "disabled"
            lines.append(
                f"- `{item.get('path')}` ({enabled}, {fmt_size(item.get('size_bytes'))}) — {item.get('reason')}"
            )
        lines.append("")
        lines.append(
            "For tasks involving scene wiring, UI bindings, serialized object references, or build-scene behavior, consider a second context bundle with `--include-editor-assets` and a higher `--max-file-mb`, or target only the needed scene with `--include-pattern`."
        )
    else:
        lines.append(
            "All scenes referenced by `ProjectSettings/EditorBuildSettings.asset` were included, or no build scenes were found."
        )
    lines.append("")

    lines.append("## Explicit include patterns")
    include_problem_count = review_flags.get(
        "explicit_include_pattern_problems_count", 0
    )
    include_patterns_count = review_flags.get("explicit_include_patterns_count", 0)
    include_problems = review_flags.get("explicit_include_pattern_problems", []) or []
    if include_problem_count:
        lines.append(
            f"{include_problem_count} explicit include pattern(s) need review because they matched no files, included no files, or had some matching files skipped:"
        )
        lines.append("")
        for item in include_problems:  # type: ignore
            lines.append(
                f"- `{item.get('pattern')}` — matched {item.get('matched_files')} file(s), "
                f"included {item.get('included_files')}, skipped {item.get('skipped_files')}"
            )
            skipped_top = item.get("skipped_top", []) or []
            for skipped in skipped_top:
                lines.append(
                    f"  - skipped `{skipped.get('path')}` ({fmt_size(skipped.get('size_bytes'))}) — {skipped.get('reason')}"
                )
        lines.append("")
        lines.append(
            "Check for typos, size-cap issues, secret/sensitive exclusions, or files that are binary/non-text."
        )
    elif include_patterns_count:
        lines.append(
            "All explicit/project-local include patterns matched at least one included file."
        )
    else:
        lines.append(
            "No explicit or project-local include patterns were used for this bundle."
        )
    lines.append("")

    lines.append("## Skipped source-like files")
    nonvendor_count = int(
        review_flags.get("skipped_nonvendor_source_like_files_count", 0) or 0  # type: ignore
    )
    vendor_count = int(
        review_flags.get("skipped_vendor_source_like_files_count", 0) or 0  # type: ignore
    )
    if nonvendor_count:
        lines.append(
            f"{nonvendor_count} non-vendor source-like file(s) were skipped. Review these before sharing the bundle:"
        )
        lines.append("")
        for item in skipped_source_top:  # type: ignore
            lines.append(
                f"- `{item.get('path')}` ({fmt_size(item.get('size_bytes'))}) — {item.get('reason')}"
            )
    else:
        lines.append("No non-vendor source-like files were skipped.")
    if vendor_count:
        lines.append(
            f"{vendor_count} source-like file(s) were skipped because they matched vendor/sample patterns. This is usually desirable for compact coding-agent bundles; use `--include-vendor-assets` or targeted `--include-pattern` only when a task needs dependency source."
        )
    lines.append("")

    lines.append("## Skipped Unity editor-authored context")
    editor_count = int(
        review_flags.get("skipped_e`ditor_authored_context_count", 0) or 0  # type: ignore
    )
    editor_bytes = int(
        review_flags.get("skipped_editor_authored_context_bytes", 0) or 0  # type: ignore
    )
    if editor_count:
        lines.append(
            f"{editor_count} first-party Unity editor-authored file(s) were skipped, totaling {format_bytes(editor_bytes)}. They are usually not edited by hand, but can be useful for understanding serialized bindings."
        )
        lines.append("")
        lines.append("Largest skipped editor-authored context files:")
        lines.append("")
        for item in editor_context_top:  # type: ignore
            lines.append(
                f"- `{item.get('path')}` ({fmt_size(item.get('size_bytes'))}) — {item.get('reason')}"
            )
    else:
        lines.append("No first-party Unity editor-authored context files were skipped.")
    lines.append("")

    lines.append("## Large included files")
    if large_included_top:
        threshold_kb = summary.get("review_large_included_kb") or "configured"
        lines.append(
            f"Included files at or above the large-file review threshold ({threshold_kb} KiB):"
        )
        lines.append("")
        for item in large_included_top:  # type: ignore
            lines.append(
                f"- `{item.get('path')}` ({fmt_size(item.get('size_bytes'))}) — {item.get('file_kind')}"
            )
    else:
        lines.append(
            "No included source/config files exceeded the large-file review threshold."
        )
    lines.append("")

    lines.append("## Suggested follow-up commands")
    lines.append("")
    project = summary.get("project_name") or project_name
    lines.append("For the normal code-only bundle:")
    lines.append("")
    lines.append(
        f"```bash\npython tools/build_unity_bundle.py {json.dumps(project)}\n```"
    )
    lines.append("")
    lines.append(
        "For a scene/prefab context pass while still excluding vendor/sample roots:"
    )
    lines.append("")
    lines.append(
        f"```bash\npython tools/build_unity_bundle.py {json.dumps(project)} --include-editor-assets --max-file-mb 2\n```"
    )
    lines.append("")
    if omitted_scenes:
        largest_scene = max(
            omitted_scenes, key=lambda item: int(item.get("size_bytes") or 0)  # type: ignore
        )  # type: ignore
        suggested_mib = max(
            2, int((int(largest_scene.get("size_bytes") or 0) / (1024 * 1024)) + 1)
        )
        scene_path = largest_scene.get("path") or "Assets/Scenes/Main.unity"
        lines.append("For only the largest omitted build scene:")
        lines.append("")
        lines.append(
            f"```bash\npython tools/build_unity_bundle.py {json.dumps(project)} --include-pattern {json.dumps(scene_path)} --max-file-mb {suggested_mib}\n```"
        )
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def summarize(
    decisions: list[Decision],
    args: argparse.Namespace,
    project_dir: Path,
    output_zip: Path,
    zip_root: str,
) -> dict:
    included = [
        d for d in decisions if d.status == "included" and d.entry_type == "file"
    ]
    skipped = [d for d in decisions if d.status == "skipped" and d.entry_type == "file"]
    errors = [d for d in decisions if d.status == "error"]

    by_kind: dict[str, int] = {}
    by_exclusion: dict[str, int] = {}
    included_roots: dict[str, dict[str, int]] = {}
    for d in decisions:
        by_kind[d.file_kind] = by_kind.get(d.file_kind, 0) + 1
        if d.status == "skipped":
            by_exclusion[d.file_kind] = by_exclusion.get(d.file_kind, 0) + 1
        if d.status == "included" and d.entry_type == "file":
            key = summary_root_key(d.rel_path)
            rec = included_roots.setdefault(key, {"files": 0, "bytes": 0})
            rec["files"] += 1
            rec["bytes"] += d.size_bytes or 0

    included_top_roots = [
        {"path": path, "files": rec["files"], "bytes": rec["bytes"]}
        for path, rec in sorted(
            included_roots.items(), key=lambda item: item[1]["bytes"], reverse=True
        )
    ]

    return {
        "tool_version": TOOL_VERSION,
        "generated_at_utc": utc_now_iso(),
        "project_name": project_dir.name,
        "project_dir": str(project_dir),
        "zip_root": zip_root,
        "output_zip": str(output_zip),
        "command": " ".join(sys.argv),
        "max_file_mib": args.max_file_mb,
        "include_editor_assets": args.include_editor_assets,
        "include_unknown_text": args.include_unknown_text,
        "include_all_meta": args.include_all_meta,
        "exclude_vendor_assets": not args.include_vendor_assets,
        "no_default_vendor_patterns": args.no_default_vendor_patterns,
        "vendor_pattern_count": len(getattr(args, "_vendor_patterns", [])),
        "full_json_manifest": args.full_json_manifest,
        "allow_binary": args.allow_binary,
        "allow_sensitive": args.allow_sensitive,
        "allow_potential_secrets": args.allow_potential_secrets,
        "prune_generated_dirs": args.prune_generated_dirs,
        "project_include_pattern_files": getattr(
            args, "_project_include_pattern_files", []
        ),
        "project_exclude_pattern_files": getattr(
            args, "_project_exclude_pattern_files", []
        ),
        "effective_include_pattern_count": getattr(
            args, "_effective_include_pattern_count", 0
        ),
        "effective_exclude_pattern_count": getattr(
            args, "_effective_exclude_pattern_count", 0
        ),
        "effective_include_patterns": getattr(args, "_effective_include_patterns", []),
        "effective_exclude_patterns": getattr(args, "_effective_exclude_patterns", []),
        "scanned_entries": len(decisions),
        "scanned_file_entries": sum(1 for d in decisions if d.entry_type == "file"),
        "included_files": len(included),
        "skipped_files": len(skipped),
        "error_entries": len(errors),
        "included_bytes": sum(d.size_bytes or 0 for d in included),
        "included_top_roots_by_bytes": included_top_roots,
        "review_large_included_kb": args.review_large_included_kb,
        "counts_by_file_kind": dict(sorted(by_kind.items())),
        "skipped_counts_by_file_kind": dict(sorted(by_exclusion.items())),
    }


def build_bundle(args: argparse.Namespace) -> tuple[Path, dict]:
    script_path = Path(__file__).resolve()
    repo_root = resolve_repo_root(script_path, args.repo_root)
    project_dir = resolve_project_dir(repo_root, args.project)
    validate_unity_project(project_dir, args.allow_non_unity)

    out_dir = args.out_dir if args.out_dir else repo_root / "artifacts" / "bundles"
    out_dir = out_dir.resolve()
    timestamp = _dt.datetime.now().strftime("%Y%m%d_%H%M%S")
    safe_project_name = (
        re.sub(r"[^A-Za-z0-9_.-]+", "_", project_dir.name).strip("_") or "unity_project"
    )
    zip_name = args.zip_name or f"{safe_project_name}_bundle_{timestamp}.zip"
    if not zip_name.lower().endswith(".zip"):
        zip_name += ".zip"
    output_zip = (out_dir / zip_name).resolve()

    if output_zip.exists() and not args.overwrite and not args.dry_run:
        raise SystemExit(
            f"Output zip already exists: {output_zip}. Use --overwrite or --zip-name."
        )

    project_include_patterns: list[str] = []
    project_exclude_patterns: list[str] = []
    project_include_sources: list[str] = []
    project_exclude_sources: list[str] = []
    if not args.ignore_project_pattern_files:
        project_include_patterns, project_include_sources = read_project_pattern_files(
            project_dir, PROJECT_INCLUDE_PATTERN_FILENAMES
        )
        project_exclude_patterns, project_exclude_sources = read_project_pattern_files(
            project_dir, PROJECT_EXCLUDE_PATTERN_FILENAMES
        )

    include_patterns = project_include_patterns + [
        normalize_pattern(p) for p in args.include_pattern
    ]
    include_patterns += read_patterns_file(args.include_from)
    exclude_patterns = project_exclude_patterns + [
        normalize_pattern(p) for p in args.exclude_pattern
    ]
    exclude_patterns += read_patterns_file(args.exclude_from)
    vendor_patterns = (
        []
        if args.no_default_vendor_patterns
        else [normalize_pattern(p) for p in DEFAULT_VENDOR_OR_SAMPLE_ASSET_PATTERNS]
    )
    vendor_patterns += [normalize_pattern(p) for p in args.vendor_pattern]
    vendor_patterns += read_patterns_file(args.vendor_from)

    args._project_include_pattern_files = project_include_sources
    args._project_exclude_pattern_files = project_exclude_sources
    args._effective_include_patterns = include_patterns
    args._effective_exclude_patterns = exclude_patterns
    args._effective_include_pattern_count = len(include_patterns)
    args._effective_exclude_pattern_count = len(exclude_patterns)
    args._vendor_patterns = vendor_patterns

    ctx = RuleContext(
        project_dir=project_dir,
        output_zip=output_zip,
        max_file_bytes=int(args.max_file_mb * 1024 * 1024),
        include_editor_assets=args.include_editor_assets,
        include_unknown_text=args.include_unknown_text,
        include_all_meta=args.include_all_meta,
        allow_binary=args.allow_binary,
        allow_sensitive=args.allow_sensitive,
        allow_potential_secrets=args.allow_potential_secrets,
        exclude_vendor_assets=not args.include_vendor_assets,
        hash_skipped=args.hash_skipped,
        include_patterns=include_patterns,
        exclude_patterns=exclude_patterns,
        vendor_patterns=vendor_patterns,
        sensitive_patterns=DEFAULT_SENSITIVE_PATTERNS,
    )

    zip_root = safe_project_name

    entries = list(
        iter_project_entries(
            project_dir, prune_generated_dirs=args.prune_generated_dirs
        )
    )
    non_meta_entries = [
        e
        for e in entries
        if not e.rel_path.endswith(".meta") and e.entry_type == "file"
    ]
    meta_entries = [
        e for e in entries if e.rel_path.endswith(".meta") and e.entry_type == "file"
    ]
    directory_entries = [e for e in entries if e.entry_type == "directory"]

    decisions_by_rel: dict[str, Decision] = {}
    decisions: list[Decision] = []

    for entry in directory_entries:
        gen_dir, gen_reason = generated_directory_reason(entry.rel_path.rstrip("/"))
        if gen_dir:
            d = skip_decision(
                entry,
                f"Pruned directory: {gen_reason} Contents were not scanned. Use --scan-generated-dirs only when you need an exhaustive generated/cache/container listing.",
                "pruned_directory",
                gen_dir,
            )
        else:
            d = skip_decision(
                entry, "Directory marker; no file content bundled.", "directory"
            )
        decisions_by_rel[entry.rel_path] = d
        decisions.append(d)

    for entry in non_meta_entries:
        try:
            decision = classify_non_meta(entry, ctx, zip_root)
        except (
            Exception
        ) as exc:  # keep manifest robust even when a file is odd/inaccessible
            decision = error_decision(entry, f"Error while classifying: {exc}")
        decisions_by_rel[entry.rel_path] = decision
        decisions.append(decision)

    included_files = {
        d.rel_path
        for d in decisions
        if d.status == "included" and d.entry_type == "file"
    }
    included_dirs = build_included_dir_set(included_files)

    for entry in meta_entries:
        try:
            decision = classify_meta(
                entry, ctx, zip_root, included_files, included_dirs
            )
        except Exception as exc:
            decision = error_decision(
                entry, f"Error while classifying .meta file: {exc}"
            )
        decisions_by_rel[entry.rel_path] = decision
        decisions.append(decision)

    # Stable order in manifests and zip.
    decisions.sort(key=lambda d: (d.rel_path.rstrip("/").lower(), d.entry_type))

    # Hash included files, and optionally skipped files. Hashing skipped files is off by default
    # so large/sensitive files are not read unnecessarily.
    for d in decisions:
        if d.entry_type != "file":
            continue
        if d.status == "included" or (d.status == "skipped" and ctx.hash_skipped):
            try:
                d.sha256 = sha256_file(project_dir / d.rel_path)
            except Exception as exc:
                if d.status == "included":
                    d.status = "error"
                    d.reason = f"Error while hashing included file: {exc}"
                    d.exclusion_reason = d.reason
                    d.file_kind = "error"
                    d.zip_path = ""

    summary = summarize(decisions, args, project_dir, output_zip, zip_root)
    review_flags = build_review_flags(decisions, project_dir, args)
    summary["review_flags"] = review_flags

    # Manifest files are generated outside first, then inserted into the bundle.
    temp_dir = out_dir / f".{safe_project_name}_bundle_tmp_{timestamp}"
    manifest_csv = temp_dir / "BUNDLE_MANIFEST.csv"
    summary_json = temp_dir / "BUNDLE_SUMMARY.json"
    manifest_json = temp_dir / "BUNDLE_MANIFEST.json"
    agent_readme = temp_dir / "README_BUNDLE.md"
    review_report = temp_dir / "BUNDLE_REVIEW_FLAGS.md"

    if args.dry_run:
        print(json.dumps(summary, indent=2, ensure_ascii=False))
        return output_zip, summary

    out_dir.mkdir(parents=True, exist_ok=True)
    temp_dir.mkdir(parents=True, exist_ok=True)
    try:
        write_manifest_csv(manifest_csv, decisions)
        write_summary_json(summary_json, summary)
        if args.full_json_manifest:
            write_manifest_json(manifest_json, decisions, summary)
        agent_readme.write_text(
            make_agent_readme(project_dir.name, summary), encoding="utf-8"
        )
        review_report.write_text(
            make_review_report(project_dir.name, summary, review_flags),
            encoding="utf-8",
        )

        compression = zipfile.ZIP_DEFLATED
        with zipfile.ZipFile(
            output_zip, "w", compression=compression, compresslevel=9
        ) as zf:
            for d in decisions:
                if d.status != "included" or d.entry_type != "file" or not d.zip_path:
                    continue
                src = project_dir / d.rel_path
                # Skip files that became problematic after classification; update console warning but
                # leave the manifest decision as the classification-time result.
                try:
                    zf.write(src, d.zip_path)
                except OSError as exc:
                    print(
                        f"Warning: could not add {d.rel_path}: {exc}", file=sys.stderr
                    )

            zf.write(agent_readme, f"{zip_root}/README_BUNDLE.md")
            zf.write(manifest_csv, f"{zip_root}/BUNDLE_MANIFEST.csv")
            zf.write(summary_json, f"{zip_root}/BUNDLE_SUMMARY.json")
            zf.write(review_report, f"{zip_root}/BUNDLE_REVIEW_FLAGS.md")
            if args.full_json_manifest:
                zf.write(manifest_json, f"{zip_root}/BUNDLE_MANIFEST.json")

        return output_zip, summary
    finally:
        # Best-effort cleanup of temporary generated manifest files.
        try:
            for p in (
                manifest_csv,
                summary_json,
                manifest_json,
                agent_readme,
                review_report,
            ):
                if p.exists():
                    p.unlink()
            temp_dir.rmdir()
        except OSError:
            pass


def positive_float(value: str) -> float:
    try:
        result = float(value)
    except ValueError as exc:
        raise argparse.ArgumentTypeError("must be a number") from exc
    if result <= 0:
        raise argparse.ArgumentTypeError("must be greater than zero")
    return result


def parse_args(argv: Optional[list[str]] = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Build a conservative zip bundle of hand-editable Unity project files for coding agents.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument(
        "project",
        help="Project name under Source/ or path to a Unity project directory.",
    )
    parser.add_argument(
        "--repo-root",
        type=Path,
        default=None,
        help="Repository/workspace root. Defaults to parent of tools/.",
    )
    parser.add_argument(
        "--out-dir",
        type=Path,
        default=None,
        help="Output directory for generated zip files.",
    )
    parser.add_argument("--zip-name", default=None, help="Custom output zip filename.")
    parser.add_argument(
        "--overwrite",
        action="store_true",
        help="Overwrite an existing zip with the same name.",
    )
    parser.add_argument(
        "--max-file-mb",
        type=positive_float,
        default=1.5,
        help="Maximum size for any included file, in MiB.",
    )
    parser.add_argument(
        "--include-editor-assets",
        action="store_true",
        help="Include text-serialized Unity editor-authored assets such as .unity, .prefab, .mat, .asset when under the size limit.",
    )
    parser.add_argument(
        "--include-unknown-text",
        action="store_true",
        help="Include unknown file extensions if they look like small text files.",
    )
    parser.add_argument(
        "--include-vendor-assets",
        action="store_true",
        help="Disable default third-party/vendor/sample asset path exclusions. Explicit include patterns also work without this flag.",
    )
    parser.add_argument(
        "--no-default-vendor-patterns",
        action="store_true",
        help="Do not apply the built-in third-party/vendor/sample asset path patterns, while still allowing --vendor-pattern/--vendor-from.",
    )
    parser.add_argument(
        "--vendor-pattern",
        action="append",
        default=[],
        help="Additional fnmatch-style path pattern to treat as vendor/sample and exclude by default, e.g. 'Assets/MyAssetStorePackage/**'. Can be repeated.",
    )
    parser.add_argument(
        "--vendor-from",
        type=Path,
        default=None,
        help="File containing additional vendor/sample exclusion patterns, one per line. # comments allowed.",
    )
    parser.add_argument(
        "--full-json-manifest",
        action="store_true",
        help="Also include full row-by-row BUNDLE_MANIFEST.json. By default, the zip includes CSV rows plus compact BUNDLE_SUMMARY.json.",
    )
    parser.add_argument(
        "--include-all-meta",
        action="store_true",
        help="Include all safe .meta files in Assets/Packages, not only companions of included files/folders.",
    )
    parser.add_argument(
        "--allow-binary",
        action="store_true",
        help="Allow binary files only when explicitly matched by --include-pattern/--include-from and under the size limit.",
    )
    parser.add_argument(
        "--allow-sensitive",
        action="store_true",
        help="Do not skip files solely because their path/name matches sensitive-file patterns. Content secret scan still applies unless --allow-potential-secrets is also used.",
    )
    parser.add_argument(
        "--allow-potential-secrets",
        action="store_true",
        help="Disable high-confidence potential-secret content exclusions. Review output manually before sharing.",
    )
    parser.add_argument(
        "--hash-skipped",
        action="store_true",
        help="Hash skipped files too. Off by default to avoid reading large/sensitive files.",
    )
    parser.add_argument(
        "--include-pattern",
        action="append",
        default=[],
        help="Additional fnmatch-style path pattern to include, e.g. 'Assets/MyDsl/**/*.foo'. Can be repeated.",
    )
    parser.add_argument(
        "--exclude-pattern",
        action="append",
        default=[],
        help="Additional fnmatch-style path pattern to exclude, e.g. 'Assets/ThirdParty/**'. Can be repeated.",
    )
    parser.add_argument(
        "--include-from",
        type=Path,
        default=None,
        help="File containing include patterns, one per line. # comments allowed.",
    )
    parser.add_argument(
        "--exclude-from",
        type=Path,
        default=None,
        help="File containing exclude patterns, one per line. # comments allowed.",
    )
    parser.add_argument(
        "--ignore-project-pattern-files",
        action="store_true",
        help="Do not automatically load .unity-bundle-include/.unity-bundle-exclude from the project root.",
    )
    parser.set_defaults(prune_generated_dirs=True)
    parser.add_argument(
        "--prune-generated-dirs",
        dest="prune_generated_dirs",
        action="store_true",
        help="Do not enumerate files inside known generated/cache/native-container dirs. This is the default.",
    )
    parser.add_argument(
        "--scan-generated-dirs",
        dest="prune_generated_dirs",
        action="store_false",
        default=argparse.SUPPRESS,
        help="Enumerate every file inside known generated/cache/native-container dirs for an exhaustive manifest. This can make manifests very large.",
    )
    parser.add_argument(
        "--top-included-roots",
        type=int,
        default=8,
        help="Print the largest included top-level roots after building. Use 0 to suppress.",
    )
    parser.add_argument(
        "--review-list-limit",
        type=int,
        default=20,
        help="Maximum number of files to list in each BUNDLE_REVIEW_FLAGS.md section.",
    )
    parser.add_argument(
        "--review-large-included-kb",
        type=int,
        default=128,
        help="Included files at or above this size are listed in BUNDLE_REVIEW_FLAGS.md for size review.",
    )
    parser.add_argument(
        "--allow-non-unity",
        action="store_true",
        help="Allow bundling a directory that does not contain Assets/ and ProjectSettings/.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Classify and print summary JSON without writing a zip.",
    )
    return parser.parse_args(argv)


def main(argv: Optional[list[str]] = None) -> int:
    args = parse_args(argv)
    try:
        output_zip, summary = build_bundle(args)
    except SystemExit:
        raise
    except Exception as exc:
        print(f"Error: {exc}", file=sys.stderr)
        return 2

    if args.dry_run:
        return 0

    print(f"Created: {output_zip}")
    print(
        f"Included {summary['included_files']} files "
        f"({summary['included_bytes']} bytes); skipped {summary['skipped_files']} files; "
        f"errors {summary['error_entries']}."
    )
    if args.top_included_roots > 0:
        roots = summary.get("included_top_roots_by_bytes", [])[
            : args.top_included_roots
        ]
        if roots:
            print("Largest included roots by uncompressed bytes:")
            for root in roots:
                print(
                    f"  {root['bytes']:>10} bytes  {root['files']:>5} files  {root['path']}"
                )
    review_flags = summary.get("review_flags", {})
    omitted_scene_count = (
        review_flags.get("omitted_build_scenes_count", 0)
        if isinstance(review_flags, dict)
        else 0
    )
    nonvendor_source_count = (
        review_flags.get("skipped_nonvendor_source_like_files_count", 0)
        if isinstance(review_flags, dict)
        else 0
    )
    include_problem_count = (
        review_flags.get("explicit_include_pattern_problems_count", 0)
        if isinstance(review_flags, dict)
        else 0
    )
    if omitted_scene_count or nonvendor_source_count or include_problem_count:
        print(
            f"Review flags: omitted build scenes={omitted_scene_count}; "
            f"skipped non-vendor source-like files={nonvendor_source_count}; "
            f"explicit include pattern issues={include_problem_count}. "
            "See BUNDLE_REVIEW_FLAGS.md inside the zip."
        )
    print(
        "Open BUNDLE_MANIFEST.csv inside the zip for every scanned file/directory and its include/exclude reason."
    )
    if not args.full_json_manifest:
        print(
            "Tip: use --full-json-manifest only when another tool needs a row-by-row JSON manifest."
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
